In [1]:
import numpy as np 


In [5]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
b= np.random.randint(1,10,(6,5))
b

array([[6, 7, 7, 7, 6],
       [5, 5, 2, 5, 1],
       [1, 7, 3, 8, 2],
       [1, 1, 1, 8, 8],
       [5, 6, 1, 8, 9],
       [7, 9, 5, 3, 6]])

In [9]:
b= np.random.randint(1,10,(6,5))
b.a+(3,3)
b

array([[3, 4, 9],
       [2, 4, 9],
       [9, 2, 7]])

In [11]:
b.reshape(-1)

array([3, 4, 9, 2, 4, 9, 9, 2, 7])

In [12]:
b

array([[3, 4, 9],
       [2, 4, 9],
       [9, 2, 7]])

In [13]:
b.flatten()

array([3, 4, 9, 2, 4, 9, 9, 2, 7])

In [14]:
print(b)
b+1

[[3 4 9]
 [2 4 9]
 [9 2 7]]


array([[ 4,  5, 10],
       [ 3,  5, 10],
       [10,  3,  8]])

In [15]:
print(b)
b-1

[[3 4 9]
 [2 4 9]
 [9 2 7]]


array([[2, 3, 8],
       [1, 3, 8],
       [8, 1, 6]])

In [16]:
print(b)
b**2

[[3 4 9]
 [2 4 9]
 [9 2 7]]


array([[ 9, 16, 81],
       [ 4, 16, 81],
       [81,  4, 49]], dtype=int32)

In [17]:
print(b)
print(b.sum())
print(b.min())
print(b.max())

[[3 4 9]
 [2 4 9]
 [9 2 7]]
49
2
9


In [18]:
print(b)
print(b.sum(axis=0))
print(b.min(axis=0))
print(b.max(axis=0))

[[3 4 9]
 [2 4 9]
 [9 2 7]]
[14 10 25]
[2 2 7]
[9 4 9]


In [19]:
print(b)
print(b.sum(axis=1))
print(b.min(axis=1))
print(b.max(axis=1))

[[3 4 9]
 [2 4 9]
 [9 2 7]]
[16 15 18]
[3 2 2]
[9 9 9]


In [20]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b=np.arange(11,17).reshape(2,3)
b

array([[11, 12, 13],
       [14, 15, 16]])

In [23]:
print(a)
print(b)
a+b

array([[12, 14, 16],
       [18, 20, 22]])

In [24]:
print(a)
print(b)
b-a

array([[10, 10, 10],
       [10, 10, 10]])

In [25]:
print(a)
print(b)
a*b


array([[11, 24, 39],
       [56, 75, 96]])

In [27]:
print(a)
print(b)
b%a

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


array([[0, 0, 1],
       [2, 0, 4]], dtype=int32)

In [28]:
c=np.random.randint(1,5,(5,3))
c

array([[1, 2, 3],
       [4, 2, 1],
       [3, 1, 1],
       [1, 3, 2],
       [1, 1, 4]])

In [29]:
np.unique(c)

array([1, 2, 3, 4])

In [32]:
d=np.sort(c)
d

array([[1, 2, 3],
       [1, 2, 4],
       [1, 1, 3],
       [1, 2, 3],
       [1, 1, 4]])

In [33]:
np.append(c,d)

array([1, 2, 3, 4, 2, 1, 3, 1, 1, 1, 3, 2, 1, 1, 4, 1, 2, 3, 1, 2, 4, 1,
       1, 3, 1, 2, 3, 1, 1, 4])

In [36]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [37]:
b=np.arange(6,10).reshape(2,2)
b

array([[6, 7],
       [8, 9]])

In [38]:
a.T #transpose

array([[1, 3],
       [2, 4]])

In [40]:
print(a)
print(b)
a.dot(b)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


array([[22, 25],
       [50, 57]])

a=np.random.randint(1,31,(6,5))
a

In [43]:
a=np.random.randint(1,31,(6,5)) 
a

array([[26, 20, 26, 18, 16],
       [20, 11,  5, 12, 28],
       [ 3, 16,  6, 17, 24],
       [29,  7,  8, 27, 26],
       [21, 26, 22, 22, 22],
       [30,  5, 30, 22, 18]])

In [44]:
a[1,2]

5

In [47]:
a[2:4,1:3]

array([[16,  6],
       [ 7,  8]])

In [45]:
a[4,2:]

array([22, 22, 22])

In [46]:
a[::-1] #reverse the array

array([[30,  5, 30, 22, 18],
       [21, 26, 22, 22, 22],
       [29,  7,  8, 27, 26],
       [ 3, 16,  6, 17, 24],
       [20, 11,  5, 12, 28],
       [26, 20, 26, 18, 16]])

In [48]:
print(a)

[[26 20 26 18 16]
 [20 11  5 12 28]
 [ 3 16  6 17 24]
 [29  7  8 27 26]
 [21 26 22 22 22]
 [30  5 30 22 18]]


In [49]:
a[a%2==1]

array([11,  5,  3, 17, 29,  7, 27, 21,  5])

In [50]:
a[a%2==0]

array([26, 20, 26, 18, 16, 20, 12, 28, 16,  6, 24,  8, 26, 26, 22, 22, 22,
       30, 30, 22, 18])

In [51]:
a[a%2==1]=9

In [52]:
print(a)

[[26 20 26 18 16]
 [20  9  9 12 28]
 [ 9 16  6  9 24]
 [ 9  9  8  9 26]
 [ 9 26 22 22 22]
 [30  9 30 22 18]]


In [53]:
a%2==1

array([[False, False, False, False, False],
       [False,  True,  True, False, False],
       [ True, False, False,  True, False],
       [ True,  True, False,  True, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False]])

20